import Feed from '../../components/Feed'
import Header from '../../components/Header'
import './globals.css'

export const metadata = {
  title: 'Instagram App ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-50 min-h-screen'>

        {/* Header */}
          <Header/>
        {/* Feed */}
          <Feed/>
        {/* Modal */}

        {children}</body>
    </html>
  )
}
